# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Werk aan de webshop
email: mark@wienkit.nl
description: > # Maak jouw webshop een groot succes met hulp van Werk aan
  de webshop.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.werkaandewebshop.com" # the base hostname & protocol for your site
twitter_username: mwienk
github_username:  werkaandewebshop

# Build settings
markdown: kramdown
timezone: Europe/Amsterdam